call plug#begin('~/.config/nvim/autoload/plugged')
  Plug 'sheerun/vim-polyglot'
  Plug 'scrooloose/NERDTree'
  Plug 'neovim/nvim-lspconfig'
  Plug 'williamboman/nvim-lsp-installer'
  Plug 'crusoexia/vim-monokai'
  Plug 'nvim-lualine/lualine.nvim'
  Plug 'terrortylor/nvim-comment'
call plug#end()
